name: Deploy
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: seanh/ghp-pelican/.github/workflows/pelican.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
